/**
 * EditableStudyGuide - Wrapper component for editable study content
 *
 * Structure:
 * - EditableTextField (Purpose) [required]
 * - EditableTextField (Context) [required]
 * - EditableThemeList
 * - Study Flow Sections
 *   - Section Header (editable)
 *   - SortableQuestionList (drag-drop reorderable)
 *   - AddQuestionButton
 * - EditableTextField (Summary)
 * - Application Questions
 *   - EditableQuestionCard (for each)
 *   - AddQuestionButton (type=application)
 * - EditableCrossReferences
 * - EditableTextField (Prayer Prompt)
 */

import { motion } from 'framer-motion';
import {
  Target,
  Map,
  Tag,
  Compass,
  FileText,
  Heart,
  BookMarked,
  MessageCircle,
  ChevronDown,
  ChevronRight,
} from 'lucide-react';
import { useState } from 'react';
import { Card, CardHeader, CardTitle, CardContent } from '../ui/Card';
import { EditableTextField } from '../ui/EditableTextField';
import { EditableThemeList } from './EditableThemeList';
import { SortableQuestionList } from './SortableQuestionList';
import { AddQuestionButton } from './AddQuestionButton';
import { EditableCrossReferences } from './EditableCrossReferences';
import { EditableQuestionCard } from './EditableQuestionCard';
import type {
  EditableStudyFull,
  EditableQuestionType,
  EditableQuestion,
  EditableCrossReference,
} from '../../types';

interface EditableStudyGuideProps {
  study: EditableStudyFull;
  provider?: string;
  passageContext?: string;  // For AI enhancement
  validationErrors?: { purpose?: string; context?: string };

  // Field updaters
  onUpdatePurpose: (value: string) => void;
  onUpdateContext: (value: string) => void;
  onUpdateSummary: (value: string) => void;
  onUpdatePrayerPrompt: (value: string) => void;

  // Theme management
  onAddTheme: (theme: string) => void;
  onUpdateTheme: (index: number, value: string) => void;
  onRemoveTheme: (index: number) => void;

  // Question management (within study flow sections)
  onAddQuestion: (sectionId: string, type: EditableQuestionType, question: string, answer?: string) => void;
  onUpdateQuestion: (sectionId: string, questionId: string, updates: Partial<EditableQuestion>) => void;
  onRemoveQuestion: (sectionId: string, questionId: string) => void;
  onReorderQuestions: (sectionId: string, fromIndex: number, toIndex: number) => void;

  // Application questions
  onAddApplicationQuestion: (question: string) => void;
  onUpdateApplicationQuestion: (id: string, updates: Partial<EditableQuestion>) => void;
  onRemoveApplicationQuestion: (id: string) => void;

  // Cross references
  onAddCrossReference: (reference: string, note: string) => void;
  onUpdateCrossReference: (id: string, updates: Partial<EditableCrossReference>) => void;
  onRemoveCrossReference: (id: string) => void;

  // Section management
  onUpdateSectionHeading: (sectionId: string, heading: string) => void;
  onUpdateSectionConnection: (sectionId: string, connection: string) => void;
}

export function EditableStudyGuide({
  study,
  provider,
  passageContext,
  validationErrors = {},
  onUpdatePurpose,
  onUpdateContext,
  onUpdateSummary,
  onUpdatePrayerPrompt,
  onAddTheme,
  onUpdateTheme,
  onRemoveTheme,
  onAddQuestion,
  onUpdateQuestion,
  onRemoveQuestion,
  onReorderQuestions,
  onAddApplicationQuestion,
  onUpdateApplicationQuestion,
  onRemoveApplicationQuestion,
  onAddCrossReference,
  onUpdateCrossReference,
  onRemoveCrossReference,
  onUpdateSectionHeading,
  onUpdateSectionConnection,
}: EditableStudyGuideProps) {
  const [expandedSections, setExpandedSections] = useState<Set<string>>(
    new Set(study.study_flow.map((s) => s.id))
  );

  const toggleSection = (sectionId: string) => {
    setExpandedSections((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(sectionId)) {
        newSet.delete(sectionId);
      } else {
        newSet.add(sectionId);
      }
      return newSet;
    });
  };

  return (
    <div className="space-y-6">
      {/* Provider Badge */}
      {provider && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="text-xs text-[var(--text-muted)] flex items-center gap-1.5"
        >
          <span className="w-1.5 h-1.5 rounded-full bg-green-500"></span>
          Generated by <span className="font-medium capitalize">{provider}</span>
        </motion.div>
      )}

      {/* Purpose */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <Card>
          <CardHeader className="flex flex-row items-center gap-2">
            <Target className="h-5 w-5 text-[var(--color-observation)]" />
            <CardTitle>Purpose</CardTitle>
          </CardHeader>
          <CardContent>
            <EditableTextField
              value={study.purpose}
              onChange={onUpdatePurpose}
              required
              error={validationErrors.purpose}
              multiline
              displayClassName="text-lg font-medium text-[var(--text-primary)] font-serif"
              placeholder="Enter the purpose of this study..."
            />
          </CardContent>
        </Card>
      </motion.div>

      {/* Context */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
      >
        <Card>
          <CardHeader className="flex flex-row items-center gap-2">
            <Map className="h-5 w-5 text-[var(--color-accent)]" />
            <CardTitle>Context</CardTitle>
          </CardHeader>
          <CardContent>
            <EditableTextField
              value={study.context}
              onChange={onUpdateContext}
              required
              error={validationErrors.context}
              multiline
              displayClassName="text-[var(--text-secondary)] leading-relaxed"
              placeholder="Enter the historical and literary context..."
            />
          </CardContent>
        </Card>
      </motion.div>

      {/* Key Themes */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
      >
        <Card>
          <CardHeader className="flex flex-row items-center gap-2">
            <Tag className="h-5 w-5 text-[var(--color-interpretation)]" />
            <CardTitle>Key Themes</CardTitle>
          </CardHeader>
          <CardContent>
            <EditableThemeList
              themes={study.key_themes}
              onUpdate={onUpdateTheme}
              onRemove={onRemoveTheme}
              onAdd={onAddTheme}
            />
          </CardContent>
        </Card>
      </motion.div>

      {/* Study Flow - Editable Sections */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.3 }}
      >
        <Card>
          <CardHeader className="flex flex-row items-center gap-2">
            <Compass className="h-5 w-5 text-[var(--color-observation)]" />
            <CardTitle>Study Guide</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-6">
              {study.study_flow.map((section, index) => {
                const isExpanded = expandedSections.has(section.id);
                return (
                  <div
                    key={section.id}
                    className="border border-[var(--border-color)] rounded-lg overflow-hidden"
                  >
                    {/* Section Header */}
                    <button
                      onClick={() => toggleSection(section.id)}
                      className="
                        w-full flex items-center justify-between
                        px-4 py-3
                        bg-[var(--bg-elevated)]
                        hover:bg-[var(--bg-surface)]
                        transition-colors
                        text-left
                      "
                    >
                      <div className="flex items-center gap-3">
                        {isExpanded ? (
                          <ChevronDown className="h-4 w-4 text-[var(--text-muted)]" />
                        ) : (
                          <ChevronRight className="h-4 w-4 text-[var(--text-muted)]" />
                        )}
                        <div>
                          <span className="text-xs font-medium text-[var(--color-interpretation)] uppercase tracking-wide">
                            {section.passage_section}
                          </span>
                          <p className="font-medium text-[var(--text-primary)] font-serif">
                            {section.section_heading}
                          </p>
                        </div>
                      </div>
                      <span className="text-xs text-[var(--text-muted)] bg-[var(--bg-main)] px-2 py-1 rounded">
                        {section.questions.length} questions
                      </span>
                    </button>

                    {/* Section Content */}
                    {isExpanded && (
                      <div className="px-4 py-4 border-t border-[var(--border-color)]">
                        {/* Section Heading Edit */}
                        <div className="mb-4">
                          <EditableTextField
                            label="Section Heading"
                            value={section.section_heading}
                            onChange={(value) => onUpdateSectionHeading(section.id, value)}
                            displayClassName="font-medium text-[var(--text-primary)]"
                          />
                        </div>

                        {/* Questions */}
                        <div className="mb-4">
                          <SortableQuestionList
                            sectionId={section.id}
                            questions={section.questions}
                            passageContext={passageContext}
                            onQuestionChange={(qId, question) =>
                              onUpdateQuestion(section.id, qId, { question })
                            }
                            onAnswerChange={(qId, answer) =>
                              onUpdateQuestion(section.id, qId, { answer })
                            }
                            onTypeChange={(qId, type) =>
                              onUpdateQuestion(section.id, qId, { type })
                            }
                            onDelete={(qId) => onRemoveQuestion(section.id, qId)}
                            onReorder={(from, to) => onReorderQuestions(section.id, from, to)}
                          />
                        </div>

                        {/* Add Question */}
                        <AddQuestionButton
                          onAdd={(type, question, answer) =>
                            onAddQuestion(section.id, type, question, answer)
                          }
                          compact
                        />

                        {/* Connection */}
                        {index < study.study_flow.length - 1 && (
                          <div className="mt-4 pt-4 border-t border-[var(--border-color)]/50">
                            <EditableTextField
                              label="Connection to Next Section"
                              value={section.connection || ''}
                              onChange={(value) => onUpdateSectionConnection(section.id, value)}
                              multiline
                              displayClassName="text-sm text-[var(--text-muted)] italic"
                              placeholder="How does this section connect to the next..."
                            />
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Summary */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.4 }}
      >
        <Card variant="elevated">
          <CardHeader className="flex flex-row items-center gap-2">
            <FileText className="h-5 w-5 text-[var(--text-muted)]" />
            <CardTitle>Summary</CardTitle>
          </CardHeader>
          <CardContent>
            <EditableTextField
              value={study.summary}
              onChange={onUpdateSummary}
              multiline
              displayClassName="text-[var(--text-secondary)] leading-relaxed"
              placeholder="Enter a summary of the passage..."
            />
          </CardContent>
        </Card>
      </motion.div>

      {/* Application Questions */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.5 }}
      >
        <Card>
          <CardHeader className="flex flex-row items-center gap-2">
            <Heart className="h-5 w-5 text-rose-500" />
            <CardTitle>Personal Application</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4 mb-4">
              {study.application_questions.map((question) => (
                <EditableQuestionCard
                  key={question.id}
                  id={question.id}
                  type={question.type}
                  question={question.question}
                  passageContext={passageContext}
                  onQuestionChange={(q) =>
                    onUpdateApplicationQuestion(question.id, { question: q })
                  }
                  onTypeChange={(t) =>
                    onUpdateApplicationQuestion(question.id, { type: t })
                  }
                  onDelete={() => onRemoveApplicationQuestion(question.id)}
                />
              ))}
            </div>
            <AddQuestionButton
              onAdd={(_type, q) => onAddApplicationQuestion(q)}
              allowedTypes={['application', 'feeling']}
              compact
            />
          </CardContent>
        </Card>
      </motion.div>

      {/* Cross References */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.6 }}
      >
        <Card>
          <CardHeader className="flex flex-row items-center gap-2">
            <BookMarked className="h-5 w-5 text-[var(--color-interpretation)]" />
            <CardTitle>Cross References</CardTitle>
          </CardHeader>
          <CardContent>
            <EditableCrossReferences
              references={study.cross_references}
              onUpdate={onUpdateCrossReference}
              onRemove={onRemoveCrossReference}
              onAdd={onAddCrossReference}
            />
          </CardContent>
        </Card>
      </motion.div>

      {/* Prayer Prompt */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.7 }}
      >
        <Card className="bg-gradient-to-br from-[var(--color-interpretation-light)] to-[var(--bg-elevated)] border-[var(--color-interpretation)]/20">
          <CardHeader className="flex flex-row items-center gap-2">
            <MessageCircle className="h-5 w-5 text-[var(--color-interpretation)]" />
            <CardTitle>Prayer Focus</CardTitle>
          </CardHeader>
          <CardContent>
            <EditableTextField
              value={study.prayer_prompt}
              onChange={onUpdatePrayerPrompt}
              multiline
              displayClassName="text-[var(--text-secondary)] italic leading-relaxed font-serif"
              placeholder="Enter a prayer focus for this passage..."
            />
          </CardContent>
        </Card>
      </motion.div>
    </div>
  );
}
