import { motion } from 'framer-motion';
import { Target, Map, Tag, Compass, FileText, Heart, BookMarked, MessageCircle } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardContent } from '../ui/Card';
import { StudyFlow } from './StudyFlow';
import { QuestionCard } from './QuestionCard';
import type { Study } from '../../types';

interface StudyGuideProps {
  study: Study;
  provider?: string;
}

export function StudyGuide({ study, provider }: StudyGuideProps) {
  if (study.error) {
    return (
      <Card className="border-red-300 bg-red-50">
        <CardContent>
          <p className="text-red-700">{study.purpose}</p>
          <p className="text-red-600 mt-2">{study.context}</p>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      {/* Provider Badge */}
      {provider && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="text-xs text-[var(--text-muted)] flex items-center gap-1.5"
        >
          <span className="w-1.5 h-1.5 rounded-full bg-green-500"></span>
          Generated by <span className="font-medium capitalize">{provider}</span>
        </motion.div>
      )}

      {/* Purpose */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <Card>
          <CardHeader className="flex flex-row items-center gap-2">
            <Target className="h-5 w-5 text-[var(--color-observation)]" />
            <CardTitle>Purpose</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-lg font-medium text-[var(--text-primary)] font-serif">
              {study.purpose}
            </p>
          </CardContent>
        </Card>
      </motion.div>

      {/* Context */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
      >
        <Card>
          <CardHeader className="flex flex-row items-center gap-2">
            <Map className="h-5 w-5 text-[var(--color-accent)]" />
            <CardTitle>Context</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-[var(--text-secondary)] leading-relaxed">{study.context}</p>
          </CardContent>
        </Card>
      </motion.div>

      {/* Key Themes */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
      >
        <Card>
          <CardHeader className="flex flex-row items-center gap-2">
            <Tag className="h-5 w-5 text-[var(--color-interpretation)]" />
            <CardTitle>Key Themes</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {study.key_themes.map((theme, index) => (
                <span
                  key={index}
                  className="theme-badge"
                >
                  {theme}
                </span>
              ))}
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Study Flow - Interwoven Questions */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.3 }}
      >
        <Card>
          <CardHeader className="flex flex-row items-center gap-2">
            <Compass className="h-5 w-5 text-[var(--color-observation)]" />
            <CardTitle>Study Guide</CardTitle>
          </CardHeader>
          <CardContent>
            <StudyFlow flow={study.study_flow} />
          </CardContent>
        </Card>
      </motion.div>

      {/* Summary */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.4 }}
      >
        <Card variant="elevated">
          <CardHeader className="flex flex-row items-center gap-2">
            <FileText className="h-5 w-5 text-[var(--text-muted)]" />
            <CardTitle>Summary</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-[var(--text-secondary)] leading-relaxed">
              {study.summary}
            </p>
          </CardContent>
        </Card>
      </motion.div>

      {/* Application Questions */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.5 }}
      >
        <Card>
          <CardHeader className="flex flex-row items-center gap-2">
            <Heart className="h-5 w-5 text-rose-500" />
            <CardTitle>Personal Application</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {study.application_questions.map((question, index) => (
                <QuestionCard
                  key={index}
                  type="application"
                  question={question}
                />
              ))}
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Cross References */}
      {study.cross_references.length > 0 && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.6 }}
        >
          <Card>
            <CardHeader className="flex flex-row items-center gap-2">
              <BookMarked className="h-5 w-5 text-[var(--color-interpretation)]" />
              <CardTitle>Cross References</CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-3">
                {study.cross_references.map((ref, index) => (
                  <li key={index} className="flex gap-3 items-start">
                    <span className="font-semibold text-[var(--color-interpretation)] whitespace-nowrap font-serif">
                      {ref.reference}
                    </span>
                    <span className="text-[var(--text-secondary)]">
                      {ref.note}
                    </span>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        </motion.div>
      )}

      {/* Prayer Prompt */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.7 }}
      >
        <Card className="bg-gradient-to-br from-[var(--color-interpretation-light)] to-[var(--bg-elevated)] border-[var(--color-interpretation)]/20">
          <CardHeader className="flex flex-row items-center gap-2">
            <MessageCircle className="h-5 w-5 text-[var(--color-interpretation)]" />
            <CardTitle>Prayer Focus</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-[var(--text-secondary)] italic leading-relaxed font-serif">
              {study.prayer_prompt}
            </p>
          </CardContent>
        </Card>
      </motion.div>
    </div>
  );
}
